---
title: "Case Study 10"
author: Alex Gould
date: November 9, 2021
output: github_document
---
 
```{r, mesage = FALSE}
library(raster)
library(rasterVis)
library(rgdal)
library(ggmap)
library(tidyverse)
library(knitr)
```


```{r}
# Create afolder to hold the downloaded data
dir.create("data",showWarnings = F)


lulc_url="https://github.com/adammwilson/DataScienceData/blob/master/inst/extdata/appeears/MCD12Q1.051_aid0001.nc?raw=true"

lst_url="https://github.com/adammwilson/DataScienceData/blob/master/inst/extdata/appeears/MOD11A2.006_aid0001.nc?raw=true"


# download them
download.file(lulc_url,destfile="data/MCD12Q1.051_aid0001.nc", mode="wb")
download.file(lst_url,destfile="data/MOD11A2.006_aid0001.nc", mode="wb")
```
```{r}
#Load Data into R 

lulc=stack("data/MCD12Q1.051_aid0001.nc",varname="Land_Cover_Type_1")

lst=stack("data/MOD11A2.006_aid0001.nc",varname="LST_Day_1km")
```
```{r}
#Explore LULC Data
plot(lulc)
```
```{r}
#Pick just one to keep things simpel
lulc <- lulc[[13]]
plot(lulc)
```

```{r}
#Assign Land Cover Classes from MODIS Website
Land_Cover_Type_1 = c(
    Water = 0, 
    `Evergreen Needleleaf forest` = 1, 
    `Evergreen Broadleaf forest` = 2,
    `Deciduous Needleleaf forest` = 3, 
    `Deciduous Broadleaf forest` = 4,
    `Mixed forest` = 5, 
    `Closed shrublands` = 6,
    `Open shrublands` = 7,
    `Woody savannas` = 8, 
    Savannas = 9,
    Grasslands = 10,
    `Permanent wetlands` = 11, 
    Croplands = 12,
    `Urban & built-up` = 13,
    `Cropland/Natural vegetation mosaic` = 14, 
    `Snow & ice` = 15,
    `Barren/Sparsely vegetated` = 16, 
    Unclassified = 254,
    NoDataFill = 255)

lcd=data.frame(
  ID=Land_Cover_Type_1,
  landcover=names(Land_Cover_Type_1),
  col=c("#000080","#008000","#00FF00", "#99CC00","#99FF99", "#339966", "#993366", "#FFCC99", "#CCFFCC", "#FFCC00", "#FF9900", "#006699", "#FFFF00", "#FF0000", "#999966", "#FFFFFF", "#808080", "#000000", "#000000"),
  stringsAsFactors = F)
# colors from https://lpdaac.usgs.gov/about/news_archive/modisterra_land_cover_types_yearly_l3_global_005deg_cmg_mod12c1
kable(head(lcd))
```
```{r}
# convert to raster (easy)
lulc=as.factor(lulc)

# update the RAT with a left join
levels(lulc)=left_join(levels(lulc)[[1]],lcd)
```


```{r}
```


## Joining, by = "ID"
```{r}
# plot it
gplot(lulc)+
  geom_raster(aes(fill=as.factor(value)))+
  scale_fill_manual(values=levels(lulc)[[1]]$col,
                    labels=levels(lulc)[[1]]$landcover,
                    name="Landcover Type")+
  coord_equal()+
  theme(legend.position = "bottom")+
  guides(fill=guide_legend(ncol=1,byrow=TRUE))
```

```{r}
plot(lst[[1:12]])
```
```{r}
offs(lst)=-273.15
plot(lst[[1:10]])
```
#Add Dates to Z (time) dimension
```{r}
names(lst)[1:5]
```
```{r}
#Convert those values to a proper R Date format by dropping the “X” and using as.Date().

tdates=names(lst)%>%
  sub(pattern="X",replacement="")%>%
  as.Date("%Y.%m.%d")

names(lst)=1:nlayers(lst)
lst=setZ(lst,tdates)

```

## [1] "X2000.02.18" "X2000.02.26" "X2000.03.05" "X2000.03.13" "X2000.03.21"
```{r}
# Define a new Spatial Point at that location
lw <-SpatialPoints(data.frame(x= -78.791547,y=43.007211)) 

#Set the projection of your point
projection(lw) <-  "+proj=longlat"

#Transform the point to the projection of the raster
spTransform(lw,CRS("+proj=longlat"))

#Extract the LST data for that location
new <- raster::extract(lst,lw,buffer=1000,fun=mean,na.rm=T) %>%
  t() %>%
#Extract Dates
  as.data.frame() %>%
  #mutate to create a new column
  mutate(date=getZ(lst))


#plot it
Part_1<- ggplot(new, aes(x=date, y=V1))+
  geom_point()+
  geom_smooth(span= .01, n=100) +
  labs(x="date", y= "Monthly Mean Land Surface Temperature")

```

```{r}
#Make a variable called tmonth
tmonth <- as.numeric(format(getZ(lst),"%m"))

#Summarize the mean value per month
lst_month <- stackApply(lst, indices = tmonth, fun=mean)

# set names of the layers to months
names(lst_month)=month.name

rasterVis::gplot(lst_month) +
  geom_tile(aes(fill = value)) +
  facet_wrap(~ variable) +
  scale_fill_gradient(low = 'blue', high = 'orange') +
  coord_equal()+
  theme_void() 
# use theme_or coord_sf(datum= NA)

#calculate monthly mean
monthly_mean <- cellStats(lst_month,mean)

#print monthly mean
monthly_mean


```


