---
title: "Case Study 11"
author: Alex Gould
date: November 16, 2021 
output: github_document
---
 
 Load Packages
```{r Load_Packages}

library(tidyverse)
library(spData)
library(sf)
library(mapview) 
library(foreach)
library(doParallel)
library(raster)

registerDoParallel(4)
getDoParWorkers() 
```
Load Census Key and Data
```{r Load_Census_Key_and_Data}

library(tidycensus)
census_api_key("010fd09f09be4dc9cf4d3f416f521716553b782c", install=TRUE, overwrite=TRUE)
```
Buffalo Demographics
```{r Buffalo_Demographics }

library(tidycensus)
racevars <- c(White = "P005003", 
              Black = "P005004", 
              Asian = "P005006", 
              Hispanic = "P004003")

options(tigris_use_cache = TRUE)

erie <- get_decennial(geography = "block", variables = racevars, 
                  state = "NY", county = "Erie County", geometry = TRUE,
                  summary_var = "P001001", cache_table=T)
```
Crop to County
```{r Crop_County}

county <- st_crop(erie, xmin=-78.9,xmax=-78.85,ymin=42.888,ymax=42.92)

```
Foreach
```{r Foreach}

x <- foreach(i=unique(county$variable),.combine='rbind') %dopar% 
  {
     county %>%
     filter(variable == i) %>%
     st_sample(size=.$value) %>%
      st_as_sf() %>%
      mutate(variable=i)
  }

```


Map
```{r View}

mapview(x, zcol = "variable", cex = 0.01, alpha = 0)

```
 
 